services:
  db:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ARm0yB4Lq2RNeAG
      MYSQL_DATABASE: golf_equipment
      MYSQL_USER: afarley
      MYSQL_PASSWORD: F6CraKpFjfbIo1
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ARm0yB4Lq2RNeAG
    ports:
      - "8080:80"

  nodeapp:
    image: addisonfarley/node-app
    container_name: nodeapp
    restart: on-failure
    ports:
      - "4242:4242"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: golf_equipment
      DB_USER: afarley
      DB_PASSWORD: F6CraKpFjfbIo1

volumes:
  mysql_data:
